name:                haskell
version:             0.1.0.0
github:              "Sir4ur0n/haskell"
license:             BSD3
author:              "Julien Debon"
maintainer:          "debon.julien@gmail.com"
copyright:           "WTFPL"

extra-source-files:
  - README.md
  - ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/Sir4ur0n/haskell#readme>

ghc-options:
  - -Wall
  - -Wcompat
  # Some additional compiler warnings from https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-home-modules
  - -Widentities
  - -Wredundant-constraints
  # Don't optimize by default (faster build time)
  - -O0

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - hlint
  - scientific
  - time
  - text
  - lens

library:
  source-dirs: src

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wmissing-home-modules
      - -Widentities
      - -Wredundant-constraints
      # Our test convention for HUnit would make it unnecessarily verbose to add the signature of each test
      - -fno-warn-missing-signatures
      # Delegate to Tasty to discover tests
      - -fno-warn-missing-export-lists
      - -fno-warn-missing-import-lists
      # Use orphan instances in tests to add Arbitrary (QuickCheck) behaviour without impacting the Production type
      - -fno-warn-orphans
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-unused-imports
      - -O0
    dependencies:
      - haskell
      # Property based testing
      - QuickCheck
      - quickcheck-instances
      - quickcheck-arbitrary-adt
      # Unit testing
      - HUnit
      # Test aggregation and discovery
      - tasty
      - tasty-quickcheck
      - tasty-hunit
      - tasty-discover
